# To create a conda environment using this file:
# conda env create -f environment.yml
name: pvcaptest
channels:
- defaults
- conda-forge
dependencies:
- holoviews>=1.14.8
- panel
- colorcet
- param
- matplotlib
- numpy
- pandas>=1*
- python>=3.8*
- python-dateutil
- statsmodels
- scikit-learn
- scipy=1.2.1
- ipython
- jupyterlab
- notebook
- pvcaptest
- nodejs # for jupyterlab pyviz extension
- openpyxl
